version: '2'
services:
  mongo-node:
        image: mongo:latest
        container_name: "mongo-node"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet          
  eureka-node:
      image: eureka-node
      build: ./eureka-node
      container_name: "eureka-node"
      links:
           - mongo-node
      ports:
        - "8761:8761"            
  config-node:
      image: config-node
      build: ./config-node
      container_name: "config-node"
      links:
           - mongo-node 
           - eureka-node
      ports:
        - "8888:8888"                  
  full-node:
      image: full-node
      build: ./full-node
      container_name: "full-node"
      links:
           - mongo-node            
           - eureka-node
           - config-node
      ports:
        - "8686:8686"      
  core-node:
      image: core-node
      build: ./core-node
      container_name: "core-node"
      links:
           - mongo-node            
           - eureka-node
           - config-node
      ports:
        - "8585:8585"
  
