version: '2'
services:
  mongo-node:
        image: mongo:latest
        container_name: "mongo-node"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet          
  eureka-node:
      image: eureka-node
      build: ./eureka-node
      container_name: "eureka-node"      
      ports:
        - "8761:8761"   
  config-node:
      image: config-node
      build: ./config-node
      container_name: "config-node"
      links:
           - eureka-node          
      ports:
        - "8888:8888"  
  turbine-node:
      image: turbine-node
      build: ./turbine-node
      container_name: "turbine-node"
      links:        
           - eureka-node                  
      ports:
        - "8082:8082"   
  hystrix-node:
      image: hystrix-node
      build: ./hystrix-node
      container_name: "hystrix-node"
      links:           
           - eureka-node
           - config-node
           - turbine-node
      ports:
        - "8081:8081"                     
  zipkin-node:
      image: zipkin-node
      build: ./zipkin-node
      container_name: "zipkin-node"
      links:           
           - eureka-node
      ports:
        - "9411:9411"                   
                  
  full-node:
      image: full-node
      build: ./full-node
      container_name: "full-node"
      links:
           - mongo-node            
           - eureka-node
           - config-node
      ports:
        - "8686:8686"      
  core-node:
      image: core-node
      build: ./core-node
      container_name: "core-node"
      links:           
           - eureka-node
           - config-node
      ports:
        - "8585:8585"
  admin-node:
      image: admin-node
      build: ./admin-node
      container_name: "admin-node"
      links:           
           - eureka-node
           - config-node
           - zipkin-node
           - turbine-node
      ports:
        - "1111:1111"        
  frontend-node:
      image: frontend-node
      build: ./frontend-node
      container_name: "frontend-node"    
      ports:
        - "9999:9999"       