version: '3'
services:
  mysqlnode:
    image: mysqlnode
    build: ./mysqlnode
    container_name: mysqlnode
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=airlines
    ports:
      - 3306:3306    
  mongonode:
    image: mongo:latest
    container_name: mongonode
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017      
    command: mongod --smallfiles --logpath=/dev/null   
  eurekanode:
    image: eurekanode
    build: ./eurekanode
    container_name: eurekanode     
    ports:
      - "8761:8761"      
  confignode:
    image: confignode
    build: ./confignode
    container_name: confignode
    links:
      - eurekanode          
    ports:
      - "8888:8888"             
  turbinenode:
    image: turbinenode
    build: ./turbinenode
    container_name: turbinenode
    links:        
      - eurekanode                  
    ports:
      - "8082:8082"           
  hystrixnode:
    image: hystrixnode
    build: ./hystrixnode
    container_name: hystrixnode
    links:           
      - eurekanode
      - confignode
      - turbinenode
    ports:
      - "8081:8081"             
  zipkinnode:
    image: zipkinnode
    build: ./zipkinnode
    container_name: zipkinnode
    links:           
      - eurekanode
    ports:
      - "9411:9411"    
  fullnode:
    image: fullnode
    build: ./fullnode
    container_name: fullnode
    links:
      - mongonode            
      - eurekanode
      - confignode
    ports:
      - "8686:8686"            
  corenode:
    image: corenode
    build: ./corenode
    container_name: corenode
    links:           
      - eurekanode
      - confignode
    ports:
      - "8585:8585"   
  airlinenode:
    image: airlinenode
    build: ./airlinenode
    container_name: airlinenode
    links:           
      - eurekanode
      - confignode
      - mysqlnode
    ports:
      - "9090:9090"            
  adminnode:
    image: adminnode
    build: ./adminnode
    container_name: adminnode
    links:           
      - eurekanode
      - confignode
      - zipkinnode
      - turbinenode
    ports:
      - "1111:1111"            
  frontend-node:
    image: frontendnode
    build: ./frontendnode
    container_name: frontendnode
    ports:         
      - "9999:9999"       
      