server:
  port: 8686
  
undertow:
   buffer-size: 1073741824
   direct-buffers: 1073741824
   io-threads: 100000
   worker-threads: 100000
   max-http-post-size: 1073741824   

spring:
  application:
    name: fullnode
    profiles:
    active:
      default
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: fullnode

hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
            
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}      