spring:
  application:
    name: full-node
  data:
    mongodb:
      host: localhost
      port: 27017
      database: full-node

server:
  port: 8686

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}