server:
  port: 9999
  contextPath: /frontend-node
jsf:
  STATE_SAVING_METHOD: server
  PROJECT_STAGE: Production
joinfaces:
  version: @project.parent.version@
spring-boot:
  version: @project.parent.parent.version@
#tomcat:
#  version: @tomcat.version@
#jetty:
#  version: @jetty.version@
undertow:
  version: @undertow.version@
cdi:
  version: @cdi.version@
mojarra:
  version: 2.3
primefaces:
  version: @primefaces.version@
  theme: le-frog



    
  
    