server:
  port: 8082

spring:
  application:
    name: turbinenode

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekanode:8761/eureka}
    healthcheck:
      enabled: false
    lease:
      duration: 5  

turbine:
  clusterNameExpression: new String("default")
  appConfig: fullnode, corenode, airlinenode
  combineHostPort: true