server:
  port: 8585

spring:
  application:
    name: corenode
    profiles:
    active:
      default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: corenode
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
  cloud:
    config:
      uri: http://192.168.99.100:8888