server:
  port: 9966

spring:
  application:
    name: zipkinnode
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: zipkinnode
      
zipkin:
  storage:
    type: mem
    #https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin-stream/src/main/resources/application.yml
    #set mysql

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
  cloud:
    config:
      uri: http://192.168.99.100:8888
      
   