server:
  port: 8686
  
undertow:
   buffer-size: 1073741824
   direct-buffers: 1073741824
   io-threads: 100000
   worker-threads: 100000
   max-http-post-size: 1073741824   

spring:
  application:
    name: fullnode
    profiles:
    active:
      default
  zipkin:
    baseUrl: http://zipkinnode:9411
    enabled: true
  sleuth:
    enabled: true
    sampler:
    percentage: 1        
  data:
    mongodb:      
      host: mongonode
      port: 27017
      database: fullnode 
  boot:
    admin:
        username: admin
        password: admin123
        url: http://adminnode:1111 

hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
            
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekanode:8761/eureka}      