server:
  port: 9987

spring:
  application:
    name: reporternode
  zipkin:
    baseUrl: http://192.168.99.100:9966
    enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reporternode

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
      
    