server:
  port: 8585

spring:
  application:
    name: corenode
  data:
    mongodb:
      host: localhost
      port: 27017
      database: corenode

full.node.url: localhost:8686

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
      ### https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html