server:
  port: 8585

spring:
  application:
    name: corenode
    zipkin:
    baseUrl: http://192.168.99.100:9966
    sleuth:
        enabled: true
        sampler:
          percentage: 1
  data:
    mongodb:      
      host: 192.168.99.100
      port: 27017
      database: corenode
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
  cloud:
    config:
      uri: http://192.168.99.100:8888      
      
      
      
      
      
      ### https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html