spring:
  application:
    name: core-node

server:
  port: 8585

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: core-node

full.node.url: localhost:8686

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}