server:
  port: 8585

spring:
  application:
    name: corenode
  data:
    mongodb:      
      host: 127.0.0.1
      port: 27017
      database: corenode
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}      
      ### https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html