server:
  port: 8585

spring:
  application:
    name: corenode
    sleuth:
        enabled: true
        sampler:
          percentage: 1
    zipkin:
        enabled: true
        baseUrl: http://192.168.99.100:9411
    data:
    mongodb:      
      host: 192.168.99.100
      port: 27017
      database: corenode   
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
#  cloud:
#    config:
#      uri: http://192.168.99.100:8888