server: 
  applicationContextPath: /core-node
  applicationConnectors:
    - type: http
      port: 8282
  adminConnectors:
    - type: http
      port: 9292
  registerDefaultExceptionMappers: true

swagger:
  resourcePackage: com.project.dropwizard.resources


#logging:
#  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: INFO
#  # Logger-specific levels.
#  loggers:
#    com.project.dropwizard: DEBUG
#    org.skife.jdbi.v2: INFO
#    org.h2: INFO
