server:
  port: 9966

spring:
  application:
    name: zipkinnode
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: zipkinnode
      
zipkin:
  storage:
    type: mem      

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.99.100:8761/eureka}
  cloud:
    config:
      uri: http://192.168.99.100:8888
      
   