server:
  port: 8761
  #host: 192.168.99.100
  host: 127.0.0.1

spring:
  application:
    name: eurekanode
  data:
    mongodb:
      host: 127.0.0.1
      #host: 192.168.99.100
      port: 27017
      database: eureka-node

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    