server:
  port: 8585
  
undertow:
   buffer-size: 1073741824
   direct-buffers: 1073741824
   io-threads: 100000
   worker-threads: 100000
   max-http-post-size: 1073741824    

management:
  security:  
    enabled: false    
    
spring:
  application:
    name: corenode
    profiles:
    active:
      default
  zipkin:
    baseUrl: http://zipkinnode:9411
    enabled: true
  sleuth:
    enabled: true
    sampler:
    percentage: 1        
  data:
    mongodb:      
      host: mongonode
      port: 27017
      database: corenode 
  boot:
    admin:
        username: admin
        password: admin123
        url: http://adminnode:1111    


            
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekanode:8761/eureka}
  cloud:
    config:
      uri: http://confignode:8888